#!/usr/bin/env bash

deindent () {
    sed -E "s/^ {$1}//"
}

deindent 4 <<EOF
    ![framegram logo](logo.svg?raw=true)

    <p align="center">
      <code>framegram</code> generates cool network packet structure diagrams </br>
        <b>with ease</b>
    </p>

    # Installation

    You can install \`framegram\` by running
    \`\`\`console
    $ python setup.py install
    \`\`\`

    This will make the \`framegram\` script available to you

    \`\`\`console
    $ framegram --help
    \`\`\`

    # Usage

    \`framegram\` uses \`*.json\` to specify the structure of the network packet, that
    will be presented.

    \`\`\`json
    $(cat tests/example_diagram2.json)
    \`\`\`

    Then you can run framegram to generate packet diagram

    \`\`\`console
    $ framegram --width 1440 --height 200 example_diagram2.json
    \`\`\`

    And this is the result

    ![frame](tests/example_diagram2.png?raw=true)

    Available options
    \`\`\`
    $ framegram --help
EOF

framegram --help

deindent 4 <<EOF
    \`\`\`
EOF
